version: '3'
services:
  cc-balance:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    volumes:
      - ./main:/app/main
    command: python main/main.py